#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorgPred3.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="datafile")]
	public partial class Datafile : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDealers(Dealers instance);
    partial void UpdateDealers(Dealers instance);
    partial void DeleteDealers(Dealers instance);
    partial void InsertLogin(Login instance);
    partial void UpdateLogin(Login instance);
    partial void DeleteLogin(Login instance);
    partial void InsertMoney(Money instance);
    partial void UpdateMoney(Money instance);
    partial void DeleteMoney(Money instance);
    partial void InsertPriceList(PriceList instance);
    partial void UpdatePriceList(PriceList instance);
    partial void DeletePriceList(PriceList instance);
    partial void InsertRefusers(Refusers instance);
    partial void UpdateRefusers(Refusers instance);
    partial void DeleteRefusers(Refusers instance);
    partial void InsertSp_statuses(Sp_statuses instance);
    partial void UpdateSp_statuses(Sp_statuses instance);
    partial void DeleteSp_statuses(Sp_statuses instance);
    partial void InsertStock(Stock instance);
    partial void UpdateStock(Stock instance);
    partial void DeleteStock(Stock instance);
    partial void InsertUploads(Uploads instance);
    partial void UpdateUploads(Uploads instance);
    partial void DeleteUploads(Uploads instance);
    partial void InsertVisits(Visits instance);
    partial void UpdateVisits(Visits instance);
    partial void DeleteVisits(Visits instance);
    #endregion
		
		public Datafile(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Datafile(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Datafile(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Datafile(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dealers> Dealers
		{
			get
			{
				return this.GetTable<Dealers>();
			}
		}
		
		public System.Data.Linq.Table<Login> Login
		{
			get
			{
				return this.GetTable<Login>();
			}
		}
		
		public System.Data.Linq.Table<Money> Money
		{
			get
			{
				return this.GetTable<Money>();
			}
		}
		
		public System.Data.Linq.Table<PriceList> PriceList
		{
			get
			{
				return this.GetTable<PriceList>();
			}
		}
		
		public System.Data.Linq.Table<Refusers> Refusers
		{
			get
			{
				return this.GetTable<Refusers>();
			}
		}
		
		public System.Data.Linq.Table<Sp_statuses> Sp_statuses
		{
			get
			{
				return this.GetTable<Sp_statuses>();
			}
		}
		
		public System.Data.Linq.Table<Stock> Stock
		{
			get
			{
				return this.GetTable<Stock>();
			}
		}
		
		public System.Data.Linq.Table<Uploads> Uploads
		{
			get
			{
				return this.GetTable<Uploads>();
			}
		}
		
		public System.Data.Linq.Table<Visits> Visits
		{
			get
			{
				return this.GetTable<Visits>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Dealers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Dealer_name;
		
		private string _Sale_point_code_new;
		
		private string _Sale_point_code_old;
		
		private string _DW;
		
		private string _RN;
		
		private int _Zone_id;
		
		private string _City;
		
		private string _Area;
		
		private string _Street;
		
		private string _House;
		
		private string _Add_comment;
		
		private string _City_type;
		
		private string _Subway_station_name;
		
		private string _Street_type;
		
		private string _House_build;
		
		private string _Contact_person;
		
		private string _Contact_phone;
		
		private int _Visit_number;
		
		private string _Sale_point_code_next;
		
		private string _TorgPred1;
		
		private string _TorgPred2;
		
		private int _Mts_price_id;
		
		private int _Beeline_price_id;
		
		private int _Megafon_price_id;
		
		private string _Sale_point_status;
		
		private int _Record_status;
		
		private string _Adr_awr;
		
		private string _Suplier_sale_point_type;
		
		private string _Sale_point_profile_type;
		
		private string _Sale_point_description;
		
		private System.Nullable<decimal> _Comm_rate;
		
		private string _Infocart_registration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnDealer_nameChanging(string value);
    partial void OnDealer_nameChanged();
    partial void OnSale_point_code_newChanging(string value);
    partial void OnSale_point_code_newChanged();
    partial void OnSale_point_code_oldChanging(string value);
    partial void OnSale_point_code_oldChanged();
    partial void OnDWChanging(string value);
    partial void OnDWChanged();
    partial void OnRNChanging(string value);
    partial void OnRNChanged();
    partial void OnZone_idChanging(int value);
    partial void OnZone_idChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnHouseChanging(string value);
    partial void OnHouseChanged();
    partial void OnAdd_commentChanging(string value);
    partial void OnAdd_commentChanged();
    partial void OnCity_typeChanging(string value);
    partial void OnCity_typeChanged();
    partial void OnSubway_station_nameChanging(string value);
    partial void OnSubway_station_nameChanged();
    partial void OnStreet_typeChanging(string value);
    partial void OnStreet_typeChanged();
    partial void OnHouse_buildChanging(string value);
    partial void OnHouse_buildChanged();
    partial void OnContact_personChanging(string value);
    partial void OnContact_personChanged();
    partial void OnContact_phoneChanging(string value);
    partial void OnContact_phoneChanged();
    partial void OnVisit_numberChanging(int value);
    partial void OnVisit_numberChanged();
    partial void OnSale_point_code_nextChanging(string value);
    partial void OnSale_point_code_nextChanged();
    partial void OnTorgPred1Changing(string value);
    partial void OnTorgPred1Changed();
    partial void OnTorgPred2Changing(string value);
    partial void OnTorgPred2Changed();
    partial void OnMts_price_idChanging(int value);
    partial void OnMts_price_idChanged();
    partial void OnBeeline_price_idChanging(int value);
    partial void OnBeeline_price_idChanged();
    partial void OnMegafon_price_idChanging(int value);
    partial void OnMegafon_price_idChanged();
    partial void OnSale_point_statusChanging(string value);
    partial void OnSale_point_statusChanged();
    partial void OnRecord_statusChanging(int value);
    partial void OnRecord_statusChanged();
    partial void OnAdr_awrChanging(string value);
    partial void OnAdr_awrChanged();
    partial void OnSuplier_sale_point_typeChanging(string value);
    partial void OnSuplier_sale_point_typeChanged();
    partial void OnSale_point_profile_typeChanging(string value);
    partial void OnSale_point_profile_typeChanged();
    partial void OnSale_point_descriptionChanging(string value);
    partial void OnSale_point_descriptionChanged();
    partial void OnComm_rateChanging(System.Nullable<decimal> value);
    partial void OnComm_rateChanged();
    partial void OnInfocart_registrationChanging(string value);
    partial void OnInfocart_registrationChanged();
    #endregion
		
		public Dealers()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dealer_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Dealer_name
		{
			get
			{
				return this._Dealer_name;
			}
			set
			{
				if ((this._Dealer_name != value))
				{
					this.OnDealer_nameChanging(value);
					this.SendPropertyChanging();
					this._Dealer_name = value;
					this.SendPropertyChanged("Dealer_name");
					this.OnDealer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_code_new", Storage="_Sale_point_code_new", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Sale_point_code_new
		{
			get
			{
				return this._Sale_point_code_new;
			}
			set
			{
				if ((this._Sale_point_code_new != value))
				{
					this.OnSale_point_code_newChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_code_new = value;
					this.SendPropertyChanged("Sale_point_code_new");
					this.OnSale_point_code_newChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_code_old", Storage="_Sale_point_code_old", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Sale_point_code_old
		{
			get
			{
				return this._Sale_point_code_old;
			}
			set
			{
				if ((this._Sale_point_code_old != value))
				{
					this.OnSale_point_code_oldChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_code_old = value;
					this.SendPropertyChanged("Sale_point_code_old");
					this.OnSale_point_code_oldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DW", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string DW
		{
			get
			{
				return this._DW;
			}
			set
			{
				if ((this._DW != value))
				{
					this.OnDWChanging(value);
					this.SendPropertyChanging();
					this._DW = value;
					this.SendPropertyChanged("DW");
					this.OnDWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RN", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string RN
		{
			get
			{
				return this._RN;
			}
			set
			{
				if ((this._RN != value))
				{
					this.OnRNChanging(value);
					this.SendPropertyChanging();
					this._RN = value;
					this.SendPropertyChanged("RN");
					this.OnRNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zone_id", DbType="Int NOT NULL")]
		public int Zone_id
		{
			get
			{
				return this._Zone_id;
			}
			set
			{
				if ((this._Zone_id != value))
				{
					this.OnZone_idChanging(value);
					this.SendPropertyChanging();
					this._Zone_id = value;
					this.SendPropertyChanged("Zone_id");
					this.OnZone_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="city", Storage="_City", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="area", Storage="_Area", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="street", Storage="_Street", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="house", Storage="_House", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string House
		{
			get
			{
				return this._House;
			}
			set
			{
				if ((this._House != value))
				{
					this.OnHouseChanging(value);
					this.SendPropertyChanging();
					this._House = value;
					this.SendPropertyChanged("House");
					this.OnHouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="add_comment", Storage="_Add_comment", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Add_comment
		{
			get
			{
				return this._Add_comment;
			}
			set
			{
				if ((this._Add_comment != value))
				{
					this.OnAdd_commentChanging(value);
					this.SendPropertyChanging();
					this._Add_comment = value;
					this.SendPropertyChanged("Add_comment");
					this.OnAdd_commentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="city_type", Storage="_City_type", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string City_type
		{
			get
			{
				return this._City_type;
			}
			set
			{
				if ((this._City_type != value))
				{
					this.OnCity_typeChanging(value);
					this.SendPropertyChanging();
					this._City_type = value;
					this.SendPropertyChanged("City_type");
					this.OnCity_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="subway_station_name", Storage="_Subway_station_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Subway_station_name
		{
			get
			{
				return this._Subway_station_name;
			}
			set
			{
				if ((this._Subway_station_name != value))
				{
					this.OnSubway_station_nameChanging(value);
					this.SendPropertyChanging();
					this._Subway_station_name = value;
					this.SendPropertyChanged("Subway_station_name");
					this.OnSubway_station_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="street_type", Storage="_Street_type", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Street_type
		{
			get
			{
				return this._Street_type;
			}
			set
			{
				if ((this._Street_type != value))
				{
					this.OnStreet_typeChanging(value);
					this.SendPropertyChanging();
					this._Street_type = value;
					this.SendPropertyChanged("Street_type");
					this.OnStreet_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="house_build", Storage="_House_build", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string House_build
		{
			get
			{
				return this._House_build;
			}
			set
			{
				if ((this._House_build != value))
				{
					this.OnHouse_buildChanging(value);
					this.SendPropertyChanging();
					this._House_build = value;
					this.SendPropertyChanged("House_build");
					this.OnHouse_buildChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_person", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Contact_person
		{
			get
			{
				return this._Contact_person;
			}
			set
			{
				if ((this._Contact_person != value))
				{
					this.OnContact_personChanging(value);
					this.SendPropertyChanging();
					this._Contact_person = value;
					this.SendPropertyChanged("Contact_person");
					this.OnContact_personChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_phone", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Contact_phone
		{
			get
			{
				return this._Contact_phone;
			}
			set
			{
				if ((this._Contact_phone != value))
				{
					this.OnContact_phoneChanging(value);
					this.SendPropertyChanging();
					this._Contact_phone = value;
					this.SendPropertyChanged("Contact_phone");
					this.OnContact_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_number", DbType="Int NOT NULL")]
		public int Visit_number
		{
			get
			{
				return this._Visit_number;
			}
			set
			{
				if ((this._Visit_number != value))
				{
					this.OnVisit_numberChanging(value);
					this.SendPropertyChanging();
					this._Visit_number = value;
					this.SendPropertyChanged("Visit_number");
					this.OnVisit_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_code_next", Storage="_Sale_point_code_next", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Sale_point_code_next
		{
			get
			{
				return this._Sale_point_code_next;
			}
			set
			{
				if ((this._Sale_point_code_next != value))
				{
					this.OnSale_point_code_nextChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_code_next = value;
					this.SendPropertyChanged("Sale_point_code_next");
					this.OnSale_point_code_nextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TorgPred1", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TorgPred1
		{
			get
			{
				return this._TorgPred1;
			}
			set
			{
				if ((this._TorgPred1 != value))
				{
					this.OnTorgPred1Changing(value);
					this.SendPropertyChanging();
					this._TorgPred1 = value;
					this.SendPropertyChanged("TorgPred1");
					this.OnTorgPred1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TorgPred2", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TorgPred2
		{
			get
			{
				return this._TorgPred2;
			}
			set
			{
				if ((this._TorgPred2 != value))
				{
					this.OnTorgPred2Changing(value);
					this.SendPropertyChanging();
					this._TorgPred2 = value;
					this.SendPropertyChanged("TorgPred2");
					this.OnTorgPred2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="mts_price_id", Storage="_Mts_price_id", DbType="Int NOT NULL")]
		public int Mts_price_id
		{
			get
			{
				return this._Mts_price_id;
			}
			set
			{
				if ((this._Mts_price_id != value))
				{
					this.OnMts_price_idChanging(value);
					this.SendPropertyChanging();
					this._Mts_price_id = value;
					this.SendPropertyChanged("Mts_price_id");
					this.OnMts_price_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="beeline_price_id", Storage="_Beeline_price_id", DbType="Int NOT NULL")]
		public int Beeline_price_id
		{
			get
			{
				return this._Beeline_price_id;
			}
			set
			{
				if ((this._Beeline_price_id != value))
				{
					this.OnBeeline_price_idChanging(value);
					this.SendPropertyChanging();
					this._Beeline_price_id = value;
					this.SendPropertyChanged("Beeline_price_id");
					this.OnBeeline_price_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="megafon_price_id", Storage="_Megafon_price_id", DbType="Int NOT NULL")]
		public int Megafon_price_id
		{
			get
			{
				return this._Megafon_price_id;
			}
			set
			{
				if ((this._Megafon_price_id != value))
				{
					this.OnMegafon_price_idChanging(value);
					this.SendPropertyChanging();
					this._Megafon_price_id = value;
					this.SendPropertyChanged("Megafon_price_id");
					this.OnMegafon_price_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_status", Storage="_Sale_point_status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sale_point_status
		{
			get
			{
				return this._Sale_point_status;
			}
			set
			{
				if ((this._Sale_point_status != value))
				{
					this.OnSale_point_statusChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_status = value;
					this.SendPropertyChanged("Sale_point_status");
					this.OnSale_point_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="record_status", Storage="_Record_status", DbType="Int NOT NULL")]
		public int Record_status
		{
			get
			{
				return this._Record_status;
			}
			set
			{
				if ((this._Record_status != value))
				{
					this.OnRecord_statusChanging(value);
					this.SendPropertyChanging();
					this._Record_status = value;
					this.SendPropertyChanged("Record_status");
					this.OnRecord_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="adr_awr", Storage="_Adr_awr", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Adr_awr
		{
			get
			{
				return this._Adr_awr;
			}
			set
			{
				if ((this._Adr_awr != value))
				{
					this.OnAdr_awrChanging(value);
					this.SendPropertyChanging();
					this._Adr_awr = value;
					this.SendPropertyChanged("Adr_awr");
					this.OnAdr_awrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="suplier_sale_point_type", Storage="_Suplier_sale_point_type", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Suplier_sale_point_type
		{
			get
			{
				return this._Suplier_sale_point_type;
			}
			set
			{
				if ((this._Suplier_sale_point_type != value))
				{
					this.OnSuplier_sale_point_typeChanging(value);
					this.SendPropertyChanging();
					this._Suplier_sale_point_type = value;
					this.SendPropertyChanged("Suplier_sale_point_type");
					this.OnSuplier_sale_point_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_profile_type", Storage="_Sale_point_profile_type", DbType="NVarChar(2)")]
		public string Sale_point_profile_type
		{
			get
			{
				return this._Sale_point_profile_type;
			}
			set
			{
				if ((this._Sale_point_profile_type != value))
				{
					this.OnSale_point_profile_typeChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_profile_type = value;
					this.SendPropertyChanged("Sale_point_profile_type");
					this.OnSale_point_profile_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_description", Storage="_Sale_point_description", DbType="NVarChar(100)")]
		public string Sale_point_description
		{
			get
			{
				return this._Sale_point_description;
			}
			set
			{
				if ((this._Sale_point_description != value))
				{
					this.OnSale_point_descriptionChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_description = value;
					this.SendPropertyChanged("Sale_point_description");
					this.OnSale_point_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="comm_rate", Storage="_Comm_rate", DbType="Money")]
		public System.Nullable<decimal> Comm_rate
		{
			get
			{
				return this._Comm_rate;
			}
			set
			{
				if ((this._Comm_rate != value))
				{
					this.OnComm_rateChanging(value);
					this.SendPropertyChanging();
					this._Comm_rate = value;
					this.SendPropertyChanged("Comm_rate");
					this.OnComm_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="infocart_registration", Storage="_Infocart_registration", DbType="NVarChar(10)")]
		public string Infocart_registration
		{
			get
			{
				return this._Infocart_registration;
			}
			set
			{
				if ((this._Infocart_registration != value))
				{
					this.OnInfocart_registrationChanging(value);
					this.SendPropertyChanging();
					this._Infocart_registration = value;
					this.SendPropertyChanged("Infocart_registration");
					this.OnInfocart_registrationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Surname;
		
		private string _Name;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Money : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private decimal _Money_sum;
		
		private System.DateTime _Money_date;
		
		private int _Money_action_id;
		
		private string _Sale_point_code_new;
		
		private string _Sale_point_code_old;
		
		private System.DateTime _Operation_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMoney_sumChanging(decimal value);
    partial void OnMoney_sumChanged();
    partial void OnMoney_dateChanging(System.DateTime value);
    partial void OnMoney_dateChanged();
    partial void OnMoney_action_idChanging(int value);
    partial void OnMoney_action_idChanged();
    partial void OnSale_point_code_newChanging(string value);
    partial void OnSale_point_code_newChanged();
    partial void OnSale_point_code_oldChanging(string value);
    partial void OnSale_point_code_oldChanged();
    partial void OnOperation_dateChanging(System.DateTime value);
    partial void OnOperation_dateChanged();
    #endregion
		
		public Money()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="money_sum", Storage="_Money_sum", DbType="Money NOT NULL")]
		public decimal Money_sum
		{
			get
			{
				return this._Money_sum;
			}
			set
			{
				if ((this._Money_sum != value))
				{
					this.OnMoney_sumChanging(value);
					this.SendPropertyChanging();
					this._Money_sum = value;
					this.SendPropertyChanged("Money_sum");
					this.OnMoney_sumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="money_date", Storage="_Money_date", DbType="DateTime NOT NULL")]
		public System.DateTime Money_date
		{
			get
			{
				return this._Money_date;
			}
			set
			{
				if ((this._Money_date != value))
				{
					this.OnMoney_dateChanging(value);
					this.SendPropertyChanging();
					this._Money_date = value;
					this.SendPropertyChanged("Money_date");
					this.OnMoney_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="money_action_id", Storage="_Money_action_id", DbType="Int NOT NULL")]
		public int Money_action_id
		{
			get
			{
				return this._Money_action_id;
			}
			set
			{
				if ((this._Money_action_id != value))
				{
					this.OnMoney_action_idChanging(value);
					this.SendPropertyChanging();
					this._Money_action_id = value;
					this.SendPropertyChanged("Money_action_id");
					this.OnMoney_action_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_code_new", Storage="_Sale_point_code_new", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Sale_point_code_new
		{
			get
			{
				return this._Sale_point_code_new;
			}
			set
			{
				if ((this._Sale_point_code_new != value))
				{
					this.OnSale_point_code_newChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_code_new = value;
					this.SendPropertyChanged("Sale_point_code_new");
					this.OnSale_point_code_newChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_code_old", Storage="_Sale_point_code_old", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Sale_point_code_old
		{
			get
			{
				return this._Sale_point_code_old;
			}
			set
			{
				if ((this._Sale_point_code_old != value))
				{
					this.OnSale_point_code_oldChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_code_old = value;
					this.SendPropertyChanged("Sale_point_code_old");
					this.OnSale_point_code_oldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operation_date", Storage="_Operation_date", DbType="DateTime NOT NULL")]
		public System.DateTime Operation_date
		{
			get
			{
				return this._Operation_date;
			}
			set
			{
				if ((this._Operation_date != value))
				{
					this.OnOperation_dateChanging(value);
					this.SendPropertyChanging();
					this._Operation_date = value;
					this.SendPropertyChanged("Operation_date");
					this.OnOperation_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class PriceList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Tp_name;
		
		private decimal _Price_n1;
		
		private decimal _Price_n2;
		
		private decimal _Price_n3;
		
		private decimal _Price_n4;
		
		private decimal _Price_n5;
		
		private decimal _Price_n6;
		
		private decimal _Price_n7;
		
		private decimal _Price_n8;
		
		private decimal _Price_n9;
		
		private decimal _Price_n10;
		
		private string _Suplier_name;
		
		private string _Product_category_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnTp_nameChanging(string value);
    partial void OnTp_nameChanged();
    partial void OnPrice_n1Changing(decimal value);
    partial void OnPrice_n1Changed();
    partial void OnPrice_n2Changing(decimal value);
    partial void OnPrice_n2Changed();
    partial void OnPrice_n3Changing(decimal value);
    partial void OnPrice_n3Changed();
    partial void OnPrice_n4Changing(decimal value);
    partial void OnPrice_n4Changed();
    partial void OnPrice_n5Changing(decimal value);
    partial void OnPrice_n5Changed();
    partial void OnPrice_n6Changing(decimal value);
    partial void OnPrice_n6Changed();
    partial void OnPrice_n7Changing(decimal value);
    partial void OnPrice_n7Changed();
    partial void OnPrice_n8Changing(decimal value);
    partial void OnPrice_n8Changed();
    partial void OnPrice_n9Changing(decimal value);
    partial void OnPrice_n9Changed();
    partial void OnPrice_n10Changing(decimal value);
    partial void OnPrice_n10Changed();
    partial void OnSuplier_nameChanging(string value);
    partial void OnSuplier_nameChanged();
    partial void OnProduct_category_nameChanging(string value);
    partial void OnProduct_category_nameChanged();
    #endregion
		
		public PriceList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tp_name", Storage="_Tp_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Tp_name
		{
			get
			{
				return this._Tp_name;
			}
			set
			{
				if ((this._Tp_name != value))
				{
					this.OnTp_nameChanging(value);
					this.SendPropertyChanging();
					this._Tp_name = value;
					this.SendPropertyChanged("Tp_name");
					this.OnTp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price_n1", Storage="_Price_n1", DbType="Money NOT NULL")]
		public decimal Price_n1
		{
			get
			{
				return this._Price_n1;
			}
			set
			{
				if ((this._Price_n1 != value))
				{
					this.OnPrice_n1Changing(value);
					this.SendPropertyChanging();
					this._Price_n1 = value;
					this.SendPropertyChanged("Price_n1");
					this.OnPrice_n1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price_n2", Storage="_Price_n2", DbType="Money NOT NULL")]
		public decimal Price_n2
		{
			get
			{
				return this._Price_n2;
			}
			set
			{
				if ((this._Price_n2 != value))
				{
					this.OnPrice_n2Changing(value);
					this.SendPropertyChanging();
					this._Price_n2 = value;
					this.SendPropertyChanged("Price_n2");
					this.OnPrice_n2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price_n3", Storage="_Price_n3", DbType="Money NOT NULL")]
		public decimal Price_n3
		{
			get
			{
				return this._Price_n3;
			}
			set
			{
				if ((this._Price_n3 != value))
				{
					this.OnPrice_n3Changing(value);
					this.SendPropertyChanging();
					this._Price_n3 = value;
					this.SendPropertyChanged("Price_n3");
					this.OnPrice_n3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price_n4", Storage="_Price_n4", DbType="Money NOT NULL")]
		public decimal Price_n4
		{
			get
			{
				return this._Price_n4;
			}
			set
			{
				if ((this._Price_n4 != value))
				{
					this.OnPrice_n4Changing(value);
					this.SendPropertyChanging();
					this._Price_n4 = value;
					this.SendPropertyChanged("Price_n4");
					this.OnPrice_n4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price_n5", Storage="_Price_n5", DbType="Money NOT NULL")]
		public decimal Price_n5
		{
			get
			{
				return this._Price_n5;
			}
			set
			{
				if ((this._Price_n5 != value))
				{
					this.OnPrice_n5Changing(value);
					this.SendPropertyChanging();
					this._Price_n5 = value;
					this.SendPropertyChanged("Price_n5");
					this.OnPrice_n5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price_n6", Storage="_Price_n6", DbType="Money NOT NULL")]
		public decimal Price_n6
		{
			get
			{
				return this._Price_n6;
			}
			set
			{
				if ((this._Price_n6 != value))
				{
					this.OnPrice_n6Changing(value);
					this.SendPropertyChanging();
					this._Price_n6 = value;
					this.SendPropertyChanged("Price_n6");
					this.OnPrice_n6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price_n7", Storage="_Price_n7", DbType="Money NOT NULL")]
		public decimal Price_n7
		{
			get
			{
				return this._Price_n7;
			}
			set
			{
				if ((this._Price_n7 != value))
				{
					this.OnPrice_n7Changing(value);
					this.SendPropertyChanging();
					this._Price_n7 = value;
					this.SendPropertyChanged("Price_n7");
					this.OnPrice_n7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price_n8", Storage="_Price_n8", DbType="Money NOT NULL")]
		public decimal Price_n8
		{
			get
			{
				return this._Price_n8;
			}
			set
			{
				if ((this._Price_n8 != value))
				{
					this.OnPrice_n8Changing(value);
					this.SendPropertyChanging();
					this._Price_n8 = value;
					this.SendPropertyChanged("Price_n8");
					this.OnPrice_n8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price_n9", Storage="_Price_n9", DbType="Money NOT NULL")]
		public decimal Price_n9
		{
			get
			{
				return this._Price_n9;
			}
			set
			{
				if ((this._Price_n9 != value))
				{
					this.OnPrice_n9Changing(value);
					this.SendPropertyChanging();
					this._Price_n9 = value;
					this.SendPropertyChanged("Price_n9");
					this.OnPrice_n9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price_n10", Storage="_Price_n10", DbType="Money NOT NULL")]
		public decimal Price_n10
		{
			get
			{
				return this._Price_n10;
			}
			set
			{
				if ((this._Price_n10 != value))
				{
					this.OnPrice_n10Changing(value);
					this.SendPropertyChanging();
					this._Price_n10 = value;
					this.SendPropertyChanged("Price_n10");
					this.OnPrice_n10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="suplier_name", Storage="_Suplier_name", DbType="NVarChar(100)")]
		public string Suplier_name
		{
			get
			{
				return this._Suplier_name;
			}
			set
			{
				if ((this._Suplier_name != value))
				{
					this.OnSuplier_nameChanging(value);
					this.SendPropertyChanging();
					this._Suplier_name = value;
					this.SendPropertyChanged("Suplier_name");
					this.OnSuplier_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="product_category_name", Storage="_Product_category_name", DbType="NVarChar(100)")]
		public string Product_category_name
		{
			get
			{
				return this._Product_category_name;
			}
			set
			{
				if ((this._Product_category_name != value))
				{
					this.OnProduct_category_nameChanging(value);
					this.SendPropertyChanging();
					this._Product_category_name = value;
					this.SendPropertyChanged("Product_category_name");
					this.OnProduct_category_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Refusers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Barcode;
		
		private System.DateTime _Refuse_date;
		
		private string _Sale_point_code_new;
		
		private string _Sale_point_code_old;
		
		private System.DateTime _Operation_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    partial void OnRefuse_dateChanging(System.DateTime value);
    partial void OnRefuse_dateChanged();
    partial void OnSale_point_code_newChanging(string value);
    partial void OnSale_point_code_newChanged();
    partial void OnSale_point_code_oldChanging(string value);
    partial void OnSale_point_code_oldChanged();
    partial void OnOperation_dateChanging(System.DateTime value);
    partial void OnOperation_dateChanged();
    #endregion
		
		public Refusers()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="barcode", Storage="_Barcode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="refuse_date", Storage="_Refuse_date", DbType="DateTime NOT NULL")]
		public System.DateTime Refuse_date
		{
			get
			{
				return this._Refuse_date;
			}
			set
			{
				if ((this._Refuse_date != value))
				{
					this.OnRefuse_dateChanging(value);
					this.SendPropertyChanging();
					this._Refuse_date = value;
					this.SendPropertyChanged("Refuse_date");
					this.OnRefuse_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_code_new", Storage="_Sale_point_code_new", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Sale_point_code_new
		{
			get
			{
				return this._Sale_point_code_new;
			}
			set
			{
				if ((this._Sale_point_code_new != value))
				{
					this.OnSale_point_code_newChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_code_new = value;
					this.SendPropertyChanged("Sale_point_code_new");
					this.OnSale_point_code_newChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_code_old", Storage="_Sale_point_code_old", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Sale_point_code_old
		{
			get
			{
				return this._Sale_point_code_old;
			}
			set
			{
				if ((this._Sale_point_code_old != value))
				{
					this.OnSale_point_code_oldChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_code_old = value;
					this.SendPropertyChanged("Sale_point_code_old");
					this.OnSale_point_code_oldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operation_date", Storage="_Operation_date", DbType="DateTime NOT NULL")]
		public System.DateTime Operation_date
		{
			get
			{
				return this._Operation_date;
			}
			set
			{
				if ((this._Operation_date != value))
				{
					this.OnOperation_dateChanging(value);
					this.SendPropertyChanging();
					this._Operation_date = value;
					this.SendPropertyChanged("Operation_date");
					this.OnOperation_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Sp_statuses : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Status_name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnStatus_nameChanging(string value);
    partial void OnStatus_nameChanged();
    #endregion
		
		public Sp_statuses()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Status_name
		{
			get
			{
				return this._Status_name;
			}
			set
			{
				if ((this._Status_name != value))
				{
					this.OnStatus_nameChanging(value);
					this.SendPropertyChanging();
					this._Status_name = value;
					this.SendPropertyChanged("Status_name");
					this.OnStatus_nameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Stock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Barcode;
		
		private string _Tp_name;
		
		private decimal _Nominal;
		
		private string _Document_num;
		
		private System.DateTime _Document_date;
		
		private System.DateTime _Operation_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    partial void OnTp_nameChanging(string value);
    partial void OnTp_nameChanged();
    partial void OnNominalChanging(decimal value);
    partial void OnNominalChanged();
    partial void OnDocument_numChanging(string value);
    partial void OnDocument_numChanged();
    partial void OnDocument_dateChanging(System.DateTime value);
    partial void OnDocument_dateChanged();
    partial void OnOperation_dateChanging(System.DateTime value);
    partial void OnOperation_dateChanged();
    #endregion
		
		public Stock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="barcode", Storage="_Barcode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tp_name", Storage="_Tp_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Tp_name
		{
			get
			{
				return this._Tp_name;
			}
			set
			{
				if ((this._Tp_name != value))
				{
					this.OnTp_nameChanging(value);
					this.SendPropertyChanging();
					this._Tp_name = value;
					this.SendPropertyChanged("Tp_name");
					this.OnTp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nominal", Storage="_Nominal", DbType="Money NOT NULL")]
		public decimal Nominal
		{
			get
			{
				return this._Nominal;
			}
			set
			{
				if ((this._Nominal != value))
				{
					this.OnNominalChanging(value);
					this.SendPropertyChanging();
					this._Nominal = value;
					this.SendPropertyChanged("Nominal");
					this.OnNominalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="document_num", Storage="_Document_num", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Document_num
		{
			get
			{
				return this._Document_num;
			}
			set
			{
				if ((this._Document_num != value))
				{
					this.OnDocument_numChanging(value);
					this.SendPropertyChanging();
					this._Document_num = value;
					this.SendPropertyChanged("Document_num");
					this.OnDocument_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="document_date", Storage="_Document_date", DbType="DateTime NOT NULL")]
		public System.DateTime Document_date
		{
			get
			{
				return this._Document_date;
			}
			set
			{
				if ((this._Document_date != value))
				{
					this.OnDocument_dateChanging(value);
					this.SendPropertyChanging();
					this._Document_date = value;
					this.SendPropertyChanged("Document_date");
					this.OnDocument_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operation_date", Storage="_Operation_date", DbType="DateTime NOT NULL")]
		public System.DateTime Operation_date
		{
			get
			{
				return this._Operation_date;
			}
			set
			{
				if ((this._Operation_date != value))
				{
					this.OnOperation_dateChanging(value);
					this.SendPropertyChanging();
					this._Operation_date = value;
					this.SendPropertyChanged("Operation_date");
					this.OnOperation_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Uploads : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Barcode;
		
		private System.DateTime _Upload_date;
		
		private string _Sale_point_code_new;
		
		private string _Sale_point_code_old;
		
		private string _Document_num;
		
		private decimal _Price;
		
		private string _Tp_name;
		
		private System.DateTime _Operation_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    partial void OnUpload_dateChanging(System.DateTime value);
    partial void OnUpload_dateChanged();
    partial void OnSale_point_code_newChanging(string value);
    partial void OnSale_point_code_newChanged();
    partial void OnSale_point_code_oldChanging(string value);
    partial void OnSale_point_code_oldChanged();
    partial void OnDocument_numChanging(string value);
    partial void OnDocument_numChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnTp_nameChanging(string value);
    partial void OnTp_nameChanged();
    partial void OnOperation_dateChanging(System.DateTime value);
    partial void OnOperation_dateChanged();
    #endregion
		
		public Uploads()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="barcode", Storage="_Barcode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="upload_date", Storage="_Upload_date", DbType="DateTime NOT NULL")]
		public System.DateTime Upload_date
		{
			get
			{
				return this._Upload_date;
			}
			set
			{
				if ((this._Upload_date != value))
				{
					this.OnUpload_dateChanging(value);
					this.SendPropertyChanging();
					this._Upload_date = value;
					this.SendPropertyChanged("Upload_date");
					this.OnUpload_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_code_new", Storage="_Sale_point_code_new", DbType="NVarChar(10)")]
		public string Sale_point_code_new
		{
			get
			{
				return this._Sale_point_code_new;
			}
			set
			{
				if ((this._Sale_point_code_new != value))
				{
					this.OnSale_point_code_newChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_code_new = value;
					this.SendPropertyChanged("Sale_point_code_new");
					this.OnSale_point_code_newChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_code_old", Storage="_Sale_point_code_old", DbType="NVarChar(10)")]
		public string Sale_point_code_old
		{
			get
			{
				return this._Sale_point_code_old;
			}
			set
			{
				if ((this._Sale_point_code_old != value))
				{
					this.OnSale_point_code_oldChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_code_old = value;
					this.SendPropertyChanged("Sale_point_code_old");
					this.OnSale_point_code_oldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="document_num", Storage="_Document_num", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Document_num
		{
			get
			{
				return this._Document_num;
			}
			set
			{
				if ((this._Document_num != value))
				{
					this.OnDocument_numChanging(value);
					this.SendPropertyChanging();
					this._Document_num = value;
					this.SendPropertyChanged("Document_num");
					this.OnDocument_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="price", Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tp_name", Storage="_Tp_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Tp_name
		{
			get
			{
				return this._Tp_name;
			}
			set
			{
				if ((this._Tp_name != value))
				{
					this.OnTp_nameChanging(value);
					this.SendPropertyChanging();
					this._Tp_name = value;
					this.SendPropertyChanged("Tp_name");
					this.OnTp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operation_date", Storage="_Operation_date", DbType="DateTime NOT NULL")]
		public System.DateTime Operation_date
		{
			get
			{
				return this._Operation_date;
			}
			set
			{
				if ((this._Operation_date != value))
				{
					this.OnOperation_dateChanging(value);
					this.SendPropertyChanging();
					this._Operation_date = value;
					this.SendPropertyChanged("Operation_date");
					this.OnOperation_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Visits : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.DateTime _Visit_date;
		
		private string _Sale_point_code_old;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnVisit_dateChanging(System.DateTime value);
    partial void OnVisit_dateChanged();
    partial void OnSale_point_code_oldChanging(string value);
    partial void OnSale_point_code_oldChanged();
    #endregion
		
		public Visits()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="visit_date", Storage="_Visit_date", DbType="DateTime NOT NULL")]
		public System.DateTime Visit_date
		{
			get
			{
				return this._Visit_date;
			}
			set
			{
				if ((this._Visit_date != value))
				{
					this.OnVisit_dateChanging(value);
					this.SendPropertyChanging();
					this._Visit_date = value;
					this.SendPropertyChanged("Visit_date");
					this.OnVisit_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sale_point_code_old", Storage="_Sale_point_code_old", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Sale_point_code_old
		{
			get
			{
				return this._Sale_point_code_old;
			}
			set
			{
				if ((this._Sale_point_code_old != value))
				{
					this.OnSale_point_code_oldChanging(value);
					this.SendPropertyChanging();
					this._Sale_point_code_old = value;
					this.SendPropertyChanged("Sale_point_code_old");
					this.OnSale_point_code_oldChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
